### ISSUE TITLE
Fix spiders not conforming to events schema

### ISSUE THREAD

**Issue by r-wei** [City-Bureau/documenters-aggregator#110]
Since we've been figuring out the [events schema](https://github.com/City-Bureau/documenters-aggregator/blob/master/docs/event_schema.md) while spiders are being made, some of the earlier spiders don't conform to the events schema. At the hackathon, I plan to go through a bunch of my old spiders and bring them up to date to the events schema.

**Comment by joshuarrrr** [comment]
Sounds good, I was thinking about this too.

**Comment by r-wei** [comment]
validation pipeline is done / a first version of the validation pipeline has been merged in
