### ISSUE TITLE
how in the ?#(!@#& are we going to easily copy airtable schema

### ISSUE THREAD

**Issue by eads** [City-Bureau/documenters-aggregator#122]

**Comment by eads** [comment]
as far as I can tell currently, we aren't!

my thought here is this: a lovely group activity for those who want to hack on the project on saturday would be building a relational database adapter

**Comment by jim** [comment]
@eads Is the issue here needing to be able to create a new "base" that contains the tables needed by out AirtablePipeline?

**Comment by jim** [comment]
From what I can tell, there is no way to create a table with the Airtable API. So this means that someone has to go in and create the destination table manually using the web GUI.

You also can't duplicate a table to another base, so this is going to have to be a manual process for now.
