### ISSUE TITLE
caps, cchhs scrapers are both a lot

### ISSUE THREAD

**Issue by eads** [City-Bureau/documenters-aggregator#132]

**Comment by eads** [comment]
@diaholliday I'm thinking that we could do some filtering in the pipeline to identify and filter out various kinds of meetings. CCHHS especially has all these community events which are lovely and we should capture somewhere but maybe no need to push into airtable. 

Past events are similar. 

Just trying to figure out ways to lighten the load on the database so there's not a lot of noise.

**Comment by diaholliday** [comment]
I agree. A lot of the those CCHHS events are not needed. My metrics are basically 1) is this a meeting where a decision that affects the city could be made and 2) is it a governing, elected or enforcement body.

I do like the CAPS meetings but we could store the CCHHS meetings without pushing them to the aggregator.

*Typed with thumbs*

**Comment by eads** [comment]
I'll filter out some of the CCHHS stuff. There's a much smaller % of the CAPS events that don't meet the criteria, but most of them do (even if there's just so many!).

I think there's some kind of basic stuff I can do like only inserting events that happen in the future, as well.

**Comment by eads** [comment]
I think this is fixed enough for now: CCHHS now grabs just the board meetings and the pipeline omits past events. There's a lot of Chicago Police events, but except for the odd fun day, fit the general criteria of meetings of official bodies with political and social consequence.
