### ISSUE TITLE
cchhs appears to return date strings that aren't legit for dateutil parser

### ISSUE THREAD

**Issue by eads** [City-Bureau/documenters-aggregator#136]
<img width="872" alt="screen shot 2017-10-09 at 1 07 43 pm" src="https://user-images.githubusercontent.com/634572/31356440-e2740c28-acf2-11e7-95c2-875d60ba5410.png">

**Comment by r-wei** [comment]
related to #133

**Comment by eads** [comment]
Lol look at me making dupes O_o
