### ISSUE TITLE
Airtable shows two different times for an event (timezone issue?)

### ISSUE THREAD

**Issue by eads** [City-Bureau/documenters-aggregator#149]
Formatted and machine readable different times

**Comment by jim** [comment]
Is this happening across the board or to a specific spider?

**Comment by eads** [comment]
Not sure -- this was reported by @diaholliday and he showed me an example but I didn't see which spider it was from. Generally speaking, a round of checking on datetimes and fixing any inconsistencies would be useful.

**Comment by diaholliday** [comment]
Across the board
![screen shot 2017-10-13 at 8 46 48 pm](https://user-images.githubusercontent.com/4017450/31730391-64d28b94-b3f7-11e7-8d36-afe6ffbb90a6.png)

looks like there's a timezone issue (or something) between "start-time-formatted" and "start-time"

**Comment by jim** [comment]
OK, that is really helpful! Next steps for the person that picks this up:

- [ ] Verify which (if either) column shows the correct time
- [ ] Check to see how the Airtable upload code is determining these values.
- [ ] Verify datetimes coming out of spiders are correct and with the right timezone info.

**Comment by pjsier** [comment]
Took a look at this, and `start_time_formatted` seems to have the right time, but `start_time` is consistently 6 hours later. From looking at the output of the Airtable pipeline on a few of the spiders, the `start_time` string seems to have the right value (the `-6:00` is consistently at the the end of the string with the right time), but Airtable seems to be converting it to UTC

**Comment by eads** [comment]
I wonder if fiddling with Airtable tz settings might resolve this. I'll take a look later.

**Comment by diaholliday** [comment]
Any update on this issue?

**Comment by jim** [comment]
@diaholliday I think this is resolved in `EventsTest`. We can test once the rollout is complete.
