### ISSUE TITLE
split location name and address into two columns

### ISSUE THREAD

**Issue by eads** [City-Bureau/documenters-aggregator#150]
/ be consistent about it

**Comment by diaholliday** [comment]
Just wanted to follow this issue so I can correct the zap when it's ready

**Comment by r-wei** [comment]
Is a change to the [events schema](https://city-bureau.gitbooks.io/documenters-event-aggregator/event-schema.html) or processing of scraped items? Right now, the events schema says the location field should have a "name" field which is the street address... I suppose that's confusing.

**Comment by diaholliday** [comment]
@r-wei yes I think it counts as a change to the events schema. Right now, the "location name" has a mix of building names and street addresses. I'd like to separate these so the address is formatted as its own column and the building name falls under "location name."

Let me know if this needs further clarification, I'm happy to refine more details.

**Comment by eads** [comment]
The original spec is confusing on this point and I'm +1 for splitting this out in a more reasonable way.  We should not forget to ping the opencivicdata people about this; I don't think their event spec is in wide use and isn't as robust as some of the other data they model. It would be nice to see an update to event spec.

**Comment by r-wei** [comment]
resolved using mapzen api
