### ISSUE TITLE
fill Nones with "n/a" in airtable pipeline

### ISSUE THREAD

**Issue by eads** [City-Bureau/documenters-aggregator#151]

**Comment by r-wei** [comment]
@diaholliday , is this something you wanted for the documenters, or @eads, is this more of a technical issue?

**Comment by diaholliday** [comment]
@r-wei  This is something I wanted for documenters. It's really just so that the space for an empty cell doesn't look blank in the email and instead lets them know that there just isn't info for that particular cell.
