### ISSUE TITLE
spell out full day / better formatting for human readable date columns

### ISSUE THREAD

**Issue by eads** [City-Bureau/documenters-aggregator#152]

**Comment by jim** [comment]
This is for Airtable I assume?

@diaholliday Can you give us an example of the format you would like to see?

**Comment by diaholliday** [comment]
Yeah it's for airtable and the associated zaps.

"Thursday, January 21, 2017" for date

and for the separate times column "11:15am"

**Comment by diaholliday** [comment]
One change here: can we put the date at the end, i.e. January 21, 2017 (Thursday).

I need to be able to sort by date and having the day of the week at the front means the Airtable filter isn't reading the date.

**Comment by jim** [comment]
@diaholliday We can do that. Would you rather have the day of the week in a separate column?

**Comment by diaholliday** [comment]
Actually yeah, that'd be great.
