### ISSUE TITLE
Rename spiders to use long names

### ISSUE THREAD

**Issue by bonfirefan** [City-Bureau/documenters-aggregator#161]
The Chicago City Clerk spider is currently named "ccc" in line with the ongoing naming convention, but the City College of Chicago has the same abbreviation. Should I change the filename ccc.py to cityclerk.py, the test to test_cityclerk, the test file to cityclerk.json, and the spidername to cityclerk, CityclerkSpider?

**Comment by r-wei** [comment]
That works for me :)

**Comment by jim** [comment]
I also like using full names instead of acronyms! It makes the codebase easier to navigate.

**Comment by eads** [comment]
Should we consider a big shift there? I added the "long name" property to help with that, but I also find the acronyms a little too obscure and a little harmful to the developer experience.

**Comment by jim** [comment]
Let's go ahead and make this change.

**Comment by jim** [comment]
@bonfirefan Do you want to tackle the renaming? If so, I'll assign this to you 😃

**Comment by bonfirefan** [comment]
@jim Hehe sure, I'll rename to more descriptive names tonight.

**Comment by bonfirefan** [comment]
"Tonight" was a blatant lie - in any case, I'm making the changes to the existing spiders and added a column for spider names in the google doc in columns "J" and "K" in the [google doc](https://docs.google.com/spreadsheets/d/1L1lbWj89wt8b2DIZhjxERJ5FCAWPDWd0nMibtc01sZk/edit#gid=0). Folks working on spiders in progress or new spiders can reference and make modification suggestions. 

I'm following (when possible) a convention of [city/county/state][servicename]. Some, like RTA, Metra, and the Local School Councils don't exactly fit this. Some agencies whose abbreviations _we_ know well - CTA, CPD etc looks strange with this convention, but it makes sense to keep to it when possible.

**Comment by jim** [comment]
@bonfirefan I usually consider "tonight" to mean "within the next week or so" on open source projects, so no worries!  😉 

Thanks for working on this, and I think the plan to use the city/state in the name makes sense. I wonder if we want to use "chicago" instead of "city", though, and "il" instead of "state" in order to keep things organized if/when we incorporate other cities and towns? There is some ongoing work to add spiders for Rockford, so I think we will encounter this situation sooner rather than later.

**Comment by bonfirefan** [comment]
Oh hmmm, I see this. I'm changing city prefixes to "chi-" and county to "cook-", state to "il-". Se

**Comment by jim** [comment]
@bonfirefan Thanks for doing this work! I merged your PR and will now close this issue.
