### ISSUE TITLE
Airtable Submission Form

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/documenters-aggregator#170]
Create custom Airtable form that will allow Documenters to claim an open public meeting sent via Zapier/the aggregator. Creation of the form will allow CB staff to begin testing Documenters management and deployment using the Airtable aggregator.

**Comment by eads** [comment]
gaaah my bad for not getting to this, I'll try and take a whack this week.

**Comment by diaholliday** [comment]
hey @jim i just wanted to quickly leave my note on formatting here before I forget. Basically, the form seems to be formatting scraped meetings differently from meetings that are manually added to the same airtable table.
![screen shot 2017-12-23 at 1 26 36 pm](https://user-images.githubusercontent.com/4017450/34322150-5c3a7e2a-e7e5-11e7-9c7a-06889ce55ed1.png)

**Comment by jim** [comment]
@diaholliday I think we addressed that in our last call. I will follow up with you to make sure it is working properly.

**Comment by jim** [comment]
Closing this issue as the form code lives in [City-Bureau/assignment-form](https://github.com/City-Bureau/assignment-form) and [City-Bureau/assignment-api](https://github.com/City-Bureau/assignment-api).
