### ISSUE TITLE
Add community area to events

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/documenters-aggregator#180]
Could set up a way to list the community area for each meeting in Airtable? I currently have an Airtable column for it but assume it's connected to the geocoding plan for the meetings.

**Comment by eads** [comment]
Whoops, didn't mean to close. Was just gonna say getting political geographies _might_ be an argument for the Texas A&M geocoder.

**Comment by easherma** [comment]
Mapzen has community areas. Other political boundaries I can't remember off the top of my head, but once we get lat/lng we can make another call to other APIs that would give us boundaries we'd like.

**Comment by jim** [comment]
We might want to have `state`, `city`, `area`, etc. fields within the `location` since we probably get most of that from the initial geocode. I'm not sure how many levels we should support, but I think looking in to the [MapZen Places API](https://mapzen.com/data/places/) is a good place to start.

**Comment by diaholliday** [comment]
@r-wei can we add this to the kanban board also?

**Comment by r-wei** [comment]
deployed yesterday using mapzen
