### ISSUE TITLE
Capitalize words in Airtable Location_Name and N/A

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/documenters-aggregator#209]
@r-wei it looks like the separation of location names and addresses is working fine but can we capitalize all the words in the location name as well as the N/A that gets added when cells are blank? i.e. "6th district police station" would be "6th District Police Station" and all the "n/a" cells would be "N/A"

**Comment by r-wei** [comment]
Yes, very doable. This should just be a couple lines of code in the airtable pipeline and using the inflector library in case others want to tackle non-spider issues
