### ISSUE TITLE
Formatting issue with start/end times

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/documenters-aggregator#215]
I've been playing around with this a bit but can't seem to figure out where the real problem lies. There's something going on between the scraped start/end times and the formula start/end times. It's possible to manually input start/end times correctly but the formula reads them wrong in the conversion
![screen shot 2018-01-06 at 11 34 14 am](https://user-images.githubusercontent.com/4017450/34642246-8eee5d5a-f2d5-11e7-83cb-30851c507c0e.png)

Long story short, the formula throws off meetings that are input manually and while the scraped meetings do seem (mostly) correct, the formula conversion renders them less useful if new meetings can't be correctly added by hand. It's generally difficult to know what the correct time is if they aren't all standardized through the same system.

Not sure what the answer here is but it;s very important that the times are correct and reliable (for obvious reasons)

**Comment by diaholliday** [comment]
I went ahead and added 6 hours to the start time on my manual inputs to get the correct formula time and here's what I have now
![screen shot 2018-01-06 at 11 54 14 am](https://user-images.githubusercontent.com/4017450/34642428-7719ea34-f2d8-11e7-8aa3-3ac17d2c0471.png)

It looks mostly correct except some of the formula times are still an hour off. Does the timezone formula conversion account for daylight savings time?

**Comment by r-wei** [comment]
resolved by #223

**Comment by diaholliday** [comment]
@jim @r-wei just wanted to check in on this closed issue. I see a "meetings test" tab in Airtable that seems to have correct start times and start time formula columns, but I don't think this has been fixed in the main meetings tab (currently we have to add 6 hours in the start time columns for it to match the Start time formula columns that are visible to Documenters on the assignment form). Can we confirm the times now match and can be applied to the main meetings tab? 

One of the side issues here is the ability to properly use the Manual Input Form for meetings without having to add 6 hours to the formula: https://airtable.com/shrAUMvvmRKcOEYmu 

Meetings test view:
![screen shot 2018-03-18 at 8 44 57 pm](https://user-images.githubusercontent.com/4017450/37574301-e65993ac-2aed-11e8-954e-468b2752210b.png)

Main Meetings view: 
![screen shot 2018-03-18 at 8 50 19 pm](https://user-images.githubusercontent.com/4017450/37574321-027f033c-2aee-11e8-8357-2e0d3c2473d8.png)
