### ISSUE TITLE
New Spider/Scraper Needed: CPS School Closure Meetings (link provided)

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/documenters-aggregator#218]
In light of the Englewood school closings I've done some research to figure out where the next meetings are being held and how we can add them to the aggregator. It looks like most, if not all of them, are listed here. Can anyone take this scraper on ASAP so we can make sure we have Documenters at them? 

I won't pretend to know how extensive this scraper will be. The meeting are located on separate tabs under a single url—but the work will be worth it. We can make sure Documenters are present: http://cps.edu/About_CPS/Policies_and_guidelines/Pages/transitionsandguidelines.aspx

**Comment by diaholliday** [comment]
Also if a coder could assess this link and let me know how difficult it would be or how long it would take that would also be much appreciated. If it's a bigger haul than I anticipated I can import the meetings by hand.

**Comment by r-wei** [comment]
This looks like a good site to scrape--all the events are formatted similarly with enough structure to pick off the different pieces. The trickiest thing will probably be navigating between the tabs. For anyone interested, a [FormRequest object](https://doc.scrapy.org/en/latest/topics/request-response.html#formrequest-objects) may be useful (see the [cook county landbank spider](https://github.com/City-Bureau/documenters-aggregator/blob/05674f989313ede2826d79a3e3e629c4295a1c07/documenters_aggregator/spiders/cook_landbank.py) for an example).

The 'school actions' and 'community submitted proposals' tabs look doable. The 'steering committee' tab looks like it only has events in the past (without locations, start and end times, etc).

**Comment by diaholliday** [comment]
If it helps, we can limit it to the "school actions" tab for now. That one is the most important but we'd need all the info in each box, including the type of closure (i.e. closure, consolidation, etc) and contact info

**Comment by pjsier** [comment]
If we're limiting to the School Actions tab this will be pretty straight forward. I thought it would be one of the weirder ASPX pages, but that tab is just an iframe for this page http://schoolinfo.cps.edu/SchoolActions/Documentation.aspx which has everything. I can work on this today if it's a priority

**Comment by diaholliday** [comment]
Yes, I'd say it's a priority for now. We're working on some other non-spider related roles for the project but the closures are timely and would be great to have available for Documenters.

**Comment by easherma** [comment]
Are these one-time meetings or recurring? 

If they are one-time meetings, then its a matter of weighing the hours spent manually entering vs writing the scraper.

**Comment by diaholliday** [comment]
One time, but I'm guessing they will keep updating this page as more closures, consolidations, etc, are announced

**Comment by diaholliday** [comment]
@r-wei i see this issue is closed but has it also been pushed to airtable? i don't see these meetings on the airtable backend but it's possible i'm overlooking it based on the name it was given.
