### ISSUE TITLE
what should the date format be? 

### ISSUE THREAD

**Issue by eads** [City-Bureau/documenters-aggregator#29]
The OpenCivicData spec is unclear on this point. To wit, "Starting date / time of the event. This should be fully timezone qualified." 

What does that even mean?

**Comment by jim** [comment]
@eads I think I'd go with ISO 8601 (e.g. `2017-08-14T15:43:39+00:00`) unless there is a good reason to use something else.

**Comment by eads** [comment]
@jim I'm with that. In the absence of more detail in the Open Civic Data spec, ISO format seems like the right way to go. Especially because libraries like pytz can calculate the correct timezone offset based on the date and Olsen timezone.

I'll add this to the docs and close when that's done.

**Comment by jim** [comment]
Turns out the OCD docs mention that the datetimes should be in UTC and use the Z timezone designator (indicating that they are in plain UTC) ([source](http://docs.opencivicdata.org/en/latest/proposals/0004.html#core-fields)):

```
Starting time of the event. This field is serialized as an ISO 8601 datetime string, normalized to UTC, and must be fully datetime aware. ISO 8601 defines times expressed in UTC with a special UTC designator (“Z”) as the timezone.
```

I added this in #73, so this can be closed when that is merged.
