### ISSUE TITLE
geolocation of all addresses/meeting locations

### ISSUE THREAD

**Issue by eads** [City-Bureau/documenters-aggregator#34]

**Comment by jim** [comment]
Can we have a stage in the pipeline that geocodes all addresses without lat/long coordinates? That way, the spiders themselves don't have to be concerned with this.

**Comment by eads** [comment]
+1 to a geocoding step in the pipeline -- we'll need to stash an address somewhere tho

**Comment by jim** [comment]
We have a geocoder now.
