### ISSUE TITLE
what to do about files genspider tests downloads

### ISSUE THREAD

**Issue by eads** [City-Bureau/documenters-aggregator#46]
@r-wei 

The genspider tests leave new files in the tests directory, somewhat out of necessity. Not a big deal but worth noting.

we could:

* ignore completely
* remove when finished
* do some mock stuff so they never get written

**Comment by jim** [comment]
If we can't find a better solution, writing the downloaded files to a `tmp` directory and adding that dir to `.gitignore` would be OK. Right now running the tests leaves the repo in a dirty state, which is not a good experience for new developers to the project.

**Comment by r-wei** [comment]
I'll fix this
