### ISSUE TITLE
invoke fails on windows

### ISSUE THREAD

**Issue by bonfirefan** [City-Bureau/documenters-aggregator#62]
`invoke runtests`
`You indicated pty=True, but your platform doesn't support the 'pty' module!`

Unfortunately pseudo terminal handling is not available for Windows, and the pty=true flag prevents you from invoking runtests. Most people are probably not doing the frustrating thing of trying to run things in Windows like I am, but just case, I know one solution mentioned was to put in an os check.

**Comment by eads** [comment]
I looked around a bit and you should be able to do something like:

```
import sys
# ...
pty = sys.platform != 'win32'
```

**Comment by eads** [comment]
I'm also wondering whether or not to file something against `invoke` ... I feel like it should warn and skip the pseudo terminal rather than bailing out, but I can see the case for how it works now.

**Comment by easherma** [comment]
I ran into similar/other issues with using windows directly. It may or may not be worth it to stub out an issue regarding Windows support/issues?

@bonfirefan were you able to get up and running? Alternative, if you're familiar with using Docker I recently added a Dockerfile that you could use to run on Windows instead

**Comment by bonfirefan** [comment]
Hey there! I would love to test out the dockerfile - I ended up switching completely to Linux, though!

**Comment by easherma** [comment]
Will do! Thanks, @bonfirefan. I too have switched totally over to Linux. 😎

**Comment by easherma** [comment]
@bonfirefan, btw, when i started using pipenv to manage dependencies this problem completely went away, even on windows!
