### ISSUE TITLE
build out data model that all scrapers / aggregators should use

### ISSUE THREAD

**Issue by eads** [City-Bureau/documenters-aggregator#7]

**Comment by fgregg** [comment]
Sorry for butting in here, but let me recommend. http://docs.opencivicdata.org/en/latest/data/event.html 

It's basically the popolo model http://www.popoloproject.com/specs/event.html

https://github.com/opencivicdata/python-opencivicdata/blob/master/opencivicdata/legislative/models/event.py#L47

**Comment by eads** [comment]
butt in away!

**Comment by eads** [comment]
This makes me wonder if I shouldn't use OpenCivicData as a framework. Scrapy is really nice though...

**Comment by fgregg** [comment]
the ocd models have a lot more than ICS/VCS. If that's all you want to target than I would just do that. 

you should be able to mix and match scrapy and the ocd models. both @gordonje and @aepton have use the models without using the rest of the stuff.

**Comment by gordonje** [comment]
Yeah, so what we're doing in [django-calaccess-processed-data](https://github.com/california-civic-data-coalition/django-calaccess-processed-data) is moving data from the models defined in calaccess_raw and calaccess_scraped into opencivicdata models (and a several others).

The Event-related models and admins are part of the legislative Django app in the opencivicdata package. So any Django project that's going to included those models needs to include both `'opencivicdata.core.apps.BaseConfig'` and `'opencivicdata.legislative.apps.BaseConfig'` in`INSTALLED_APPS` in `settings.py`. As we were developing the elections models and admins, there was some talk about the need for a more generic base Event model to be included in core, but we punted on that.

**Comment by eads** [comment]
This is helpful. I think it makes sense for us to use the OCD model internally, since we'll be consuming HTML/ical/vcs/rss/who-the-heck-knows into a central db and then serializing output in whatever ways appear to be useful.

In fact, I've already coded it up (but have yet to push).

**Comment by eads** [comment]
Rolling with OCD. Closed in favor of #10
