### ISSUE TITLE
OCD Spider: Cook County Board of Comissioners

### ISSUE THREAD

**Issue by r-wei** [City-Bureau/documenters-aggregator#78]
Step 1: To access the data, guess the name of the client here: http://webapi.legistar.com/
The name of the client is not:
cookcounty
cook-county
cookcountyil
cookcountygov
cookcountygovil
cookcountyilgov

**Comment by r-wei** [comment]
I emailed the webmaster last week asking if their data is public, but no response yet.

**Comment by eads** [comment]
Time for some FOIA action?

**Comment by fgregg** [comment]
Only a very few legistar sites have their data exposed through the API. Cook County is not one of them.

I don't think A FOIA will help you since they publish the data here: https://cook-county.legistar.com/Calendar.aspx
