### ISSUE TITLE
Estimating unknown end_time?

### ISSUE THREAD

**Issue by joshuarrrr** [City-Bureau/documenters-aggregator#88]
Some meetings have no defined length, but end_time is a required field. 
Should we use some default duration like
`start_time + timedelta(hours=1)`
for such meetings? 

If so, maybe add to FAQ #87

**Comment by r-wei** [comment]
Our work-in-progress [events schema](https://github.com/City-Bureau/documenters-aggregator/blob/master/docs/event_schema.md) allows optional end times. I think this question is best answered by the documenters: @diaholliday ?

**Comment by eads** [comment]
👍 @r-wei -- definitely a bigger fan of changing the specification than trying to guess something we don't know.

**Comment by joshuarrrr** [comment]
@r-wei Thanks for the link to the events schema, that's really helpful. 

@eads I agree that it makes sense to limit the not make inferences at this stage of the pipeline. I guess I was thinking ahead to the way calendar interfaces usually have some default duration set for representing times. But better done downstream.
